<div class="form">
    <form action="<?php echo $this->getUrl('admin/catalog_product/save') ?>" method="post" enctype="multipart/form-data">

        <!-- Hidden field for product_id -->
        <input type="hidden" name="catalog_product[product_id]" value="<?php echo $this->data->getProductId() ?>">

        <!-- SKU -->
        <label for="sku">SKU:</label>
        <input type="text" name="catalog_product[sku]" id="sku" value="<?php echo $this->data->getSku() ?>" required>
        <br>

        <!-- Name -->
        <label for="name">Name:</label>
        <input type="text" name="catalog_product[name]" id="name" value="<?php echo $this->data->getName() ?>" required>
        <br>

        <!-- Color -->
        <label for="color">Color:</label>
        <input type="text" name="catalog_product[color]" id="color" value="<?php echo $this->data->getColor() ?>" required>
        <br>

        <!-- Size -->
        <label for="size">Size:</label>
        <input type="text" name="catalog_product[size]" id="size" value="<?php echo $this->data->getSize() ?>" required>
        <br>

        <!-- Description -->
        <label for="description">Description:</label>
        <textarea name="catalog_product[description]" id="description" value="<?php echo $this->data->getDescription() ?>" required><?php echo $this->data->getDescription() ?></textarea>
        <br>

        <!-- Image -->
        <label for="image">Image:</label>
        <input type="file" name="catalog_product[image_link]" id="image" value="<?php echo $this->data->getImage() ?>" accept="image/*">
        <br>
        <?php
        if (!is_null($this->data->getImageLink())) {
            echo "<img src='" . Mage::getBaseUrl('media/banner/') . $this->data->getBannerImage() . "' alt='Uploaded Image' height=100px width=200px>";
        }
        ?>

        <!-- Link -->
        <label for="link">Link:</label>
        <input type="text" name="catalog_product[link]" id="link" value="<?php echo $this->data->getLink() ?>" required>
        <br>

        <!-- Category dropdown -->
        <label for="category">Category:</label>
        <select name="catalog_product[category_id]" id="category">
            <?php
            $categories = Mage::getModel('catalog/category')->getCollection()->addFieldToFilter('status','1')->getData();
            foreach ($categories as $category) {
                echo '<option value=" ' . $category->getCategoryId() . '">' . $category->getCategoryName() . '</option>';
            }
            ?>
        </select>
        <br>


        <!-- Price -->
        <label for="price">Price:</label>
        <input type="text" name="catalog_product[price]" id="price" value="<?php echo $this->data->getPrice() ?>" required>

        <br>

        <!-- Mfr Cost -->
        <label for="mfr_cost">Manufacturer Cost:</label>
        <input type="text" name="catalog_product[mfr_cost]" id="mfr_cost" value="<?php echo $this->data->getMfrCost() ?>" required>
        <br>

        <!-- Shipping Cost -->
        <label for="shipping_cost">Shipping Cost:</label>
        <input type="text" name="catalog_product[shipping_cost]" id="shipping_cost" value="<?php echo $this->data->getShippingCost() ?>" required>
        <br>

        <!-- Total Cost -->
        <label for="total_cost">Total Cost:</label>
        <input type="text" name="catalog_product[total_cost]" id="total_cost" value="<?php echo $this->data->getTotalCost() ?>" required>
        <br>

        <!-- Margin Percentage -->
        <label for="margin_percentage">Margin Percentage:</label>
        <input type="text" name="catalog_product[margin_percentage]" id="margin_percentage" value="<?php echo $this->data->getMarginPercentage() ?>" required>
        <br>

        <!-- Min Price -->
        <label for="min_price">Min Price:</label>
        <input type="text" name="catalog_product[min_price]" id="min_price" value="<?php echo $this->data->getMinPrice() ?>" required>
        <br>

        <!-- Status dropdown -->
        <div class="row">
            <label for="status">Status:</label>
            <select name="catalog_product[status]" id="status">
                <option value="1" <?php echo ($this->data->getStatus() === 'Enable') ? 'selected' : ''; ?>>Enable</option>
                <option value="0" <?php echo ($this->data->getStatus() === 'Disable') ? 'selected' : ''; ?>>Disable</option>
            </select>
        </div>

        <!-- Submit button -->
        <input type="submit" value="Submit">

    </form>
</div>