<div class="container">
    <?php $product = Mage::getModel('bmiCalculator/bmiCalculator')->getCollection()->addFieldToFilter('session_id',$this->sessionId())->getData()?>
    <form method="post" action="<?php echo $this->getUrl('bmiCalculator/calculate/save') ?>">
    <?php var_dump($product)?>
        <input type="hidden" id="id" name="bmi[id_value]" value="<?php echo !is_null($this->data->getIdValue()) ? $this->data->getIdValue() : '' ?>">
        <input type="hidden" id="id1" name="bmi[session_id]" value="<?php echo !is_null($this->sessionId()) ? $this->sessionId() : '' ?>">
        <div class="form-field">
            <label for="user_name">Category Name:</label>
            <input type="text" id="user_name" name="bmi[user_name]" placeholder="Enter user name" value="<?php echo isset($product['user_name']) ? $product['user_name'] : '' ?>">
        </div>

        <div class="form-field">
            <label for="weight">Weight:</label>
            <input type="number" id="weight" name="bmi[weight]" placeholder="weight" value="">
        </div>
        <select name="bmi[weight_value]">
            <?php foreach ($this->getWeightMeasure() as $weight)
                echo '<option value="' . $weight . '">' . $weight . '</option>';
            ?>
        </select>

        <div class="form-field">
            <label for="height">Height:</label>
            <input type="number" id="height" name="bmi[height]" placeholder="height" value="">
        </div>
        <select name="bmi[height_value]">
            <?php foreach ($this->getHeightMeasure() as $height)
                echo '<option value="' . $height . '">' . $height . '</option>';
            ?>
        </select>

        <button type="submit">Submit</button>
    </form>
</div>
