<div class="product-container">
    <?php $products = $this->data; ?>

    <?php foreach ($products as $product) : ?>
        <div class="product-card">
            <img src="<?php echo $this->getUrl('media/category/') . $product->getImageLink() ?>" alt="Product Image" class="product-image">
            <h3 class="product-title"><?php echo $product->getName(); ?></h3>
            <p class="product-description"><?php echo $product->getDescription(); ?></p>
            <span class="product-price"><?php echo $product->getPrice(); ?></span>
            <button class="add-to-cart"><a href="<?php echo Mage::getBaseUrl('catalog/product/view?id=' . $product->getProductId()) ?>">View Product</a></button>
        </div>
    <?php endforeach; ?>
</div>