<header>
    <div class="logo">
        <img src="\practice\mvc\skin\images\images.png" alt="Logo">
    </div>
    <nav>
        <!-- <input type="text" placeholder="Search"> -->
        <ul>
            <li><a href="<?php echo $this->getUrl('admin/catalog_product/list') ?>">Product List</a></li>
            <li><a href="<?php echo $this->getUrl('admin/catalog_category/list') ?>">Categorie List</a></li>
            <li><a href="<?php echo $this->getUrl('admin/catalog_category/form') ?>">Categorie Form</a></li>
            <li><a href="<?php echo $this->getUrl('admin/catalog_product/form') ?>">Product Form</a></li>
            <li><a href="<?php echo $this->getUrl('admin/banner/form') ?>">Banner Form</a></li>
            <li><a href="<?php echo $this->getUrl('admin/banner/list') ?>">Banner List</a></li>
            <li><a href="<?php echo $this->getUrl('admin/order_list/list') ?>">Order List</a></li>
            <li><a href="<?php echo $this->getUrl('admin/user/logOut') ?>">Log Out</a></li>
        </ul>
    </nav>
</header>