<div class="product-container">
    <div class="product-details">
        <h2><?php echo $this->data->getName() ?></h2>
        <p><strong>Color:</strong><?php echo $this->data->getColor(); ?></p>
        <p><strong>Size:</strong><?php echo $this->data->getSize(); ?></p>
        <p><strong>Description:</strong><?php echo $this->data->getDescription(); ?></p>
        <p><strong>Price:</strong><?php echo $this->data->getPrice(); ?></p>
        <p><strong>Status:</strong><?php echo $this->data->getStatus(); ?></p>
        <form action="<?php echo $this->getUrl('sales/quote/add')?>" method="post">
            <input type="hidden" id="product_id" name="cart[product_id]" value="<?php echo $this->data->getProductId()?>">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="cart[quantity]" placeholder="Enter quantity" min="1" value="1" required>
            <input type="submit" value="Add to Cart">
        </form>
    </div>
</div>